apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- ingress.yaml
configMapGenerator:
- name: emojicode-playground
  files:
  - image=emoji.png
  literals:
  - name=Emojicode Playground
  - description=Execute emojicode programs live on the web!
  - url=https://emojicode.telliott.io
  namespace: projectlist
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated